### ISSUE TITLE
Wrong apple_id use when combined with project that has existing fastlane

### ISSUE THREAD

**Issue by LeBlaaanc** [bitrise-io/steps-deploy-to-itunesconnect-deliver#11]
When using this step combined with a project that has a `fastlane/Appfile` it seems to use the apple_id in that file instead of what is specified via the `itunescon_user` param.

**Comment by viktorbenei** [comment]
could you please create a bug at https://github.com/fastlane/fastlane ? we can't fix this on our side unfortunately

**Comment by viktorbenei** [comment]
`deliver`, when used without `fastlane` should ignore the `fastlane` directory, but it seems it does not

**Comment by LeBlaaanc** [comment]
@viktorbenei oh I see my mistake will add it there and reference.

**Comment by viktorbenei** [comment]
Thank you! :)
