### ISSUE TITLE
clarification of submit to testflight beta options.

### ISSUE THREAD

**Issue by 50chickens** [bitrise-io/steps-deploy-to-itunesconnect-deliver#12]
i think the itunes connect site has changed slightly since this code was written. 

curently, on the itunes connect website (itunesconnect.apple.com), there 4 sections (app store, features, testflight, activity). the corrosponding option in steps-deploy-to-itunesconnect-deliver are 'Submit for TestFlight Beta Testing?'. 

if you choose 'Submit for TestFlight Beta Testing?' then what it does it upload it internal testflight section, and also (by the looks) to the external test section under testflight. 

The issue is that i think people will think they need to enable the 'submit for testflight beta' to just get it uploaded to the (internal) testflight section. However, they only want this when they want to submit it to the external testers section (which can have a 'beta app review' requirement). 

My suggestion:

'beta testing' in the step description really should be called 'add to external testing' to reflect the current layout/workflow of the itunes connect website.

**Comment by viktorbenei** [comment]
Thanks for reporting, we'll push an update for the step next week! ;)

**Comment by godrei** [comment]
Hi @50chickens thanks for the report. The new version [2.6.3](https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/releases/tag/2.6.3) contains description updates.
