### ISSUE TITLE
Fails to upload TVOS builds

### ISSUE THREAD

**Issue by bitwit** [bitrise-io/steps-deploy-to-itunesconnect-deliver#14]
It appears that the parameters provided during upload to the Apple APIs must be implying that the build is for an iOS app.

I recently tried to make a TVOS upload and got `The version number has been previously used.` as a failure reason. This would only be true if it were comparing against the iOS version/build number though.

**Comment by viktorbenei** [comment]
You should report this on `deliver`'s GitHub (https://github.com/fastlane/fastlane/tree/master/deliver) - this step is just a thin wrapper around `deliver`, it just passes the IPA path and auth infos to `deliver`, after that the actual uploading is done by `deliver`.
