### ISSUE TITLE
Update fastlane Failed

### ISSUE THREAD

**Issue by Shinichi52** [bitrise-io/steps-deploy-to-itunesconnect-deliver#24]
Hi,
Last weekend, I'm build successful. But in this morning i tried build, it's failed with alert error:

Setup
fastlane already installed
updating fastlane...
Failed to install 'fastlane', error: Gem update failed, error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-deliver@2.9.2 (exit code: 1)          | 12 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...om/bitrise-io/steps-deploy-to-itunesconnect-deliver/issues |
| Source: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver  |
+---+---------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
Did you try a rebuild? It seems to be a temporary network issue, most likely on the Ruby gems server side

**Comment by viktorbenei** [comment]
I think the best we could do is adding a re-try mechanism here, so that if the Ruby GEMs server has only a very short issue a second attempt might be successful. Added to backlog.

**Comment by Shinichi52** [comment]
Hi, 
Thanks for fast supported. I tried re-build about 3-5 times in this day. but it's failed with the same error (I builded it at locally). Are you have solution for me?

**Comment by viktorbenei** [comment]
Can you please send us the build's bitrise.io url? Feel free to send it in email or through the onsite chat

**Comment by Shinichi52** [comment]
I built it at locally with bitrise-cli and this is my project at bitrise.io https://www.bitrise.io/app/41335a3ce50b7dc4#/builds

**Comment by Shinichi52** [comment]
Hi. I updated manual fastlane and it's working now. Thanks for supported :)

**Comment by viktorbenei** [comment]
Any time ;)

May I ask what you changed/did? Might help others, as well as us (built in support or better log etc)

**Comment by Shinichi52** [comment]
i fixed it with command: sudo gem install -n /usr/local/bin fastlane

**Comment by viktorbenei** [comment]
Makes sense, thanks for the info @Shinichi52 ! :)

If I might ask, did you do that (the fix) locally on your Mac, or on Bitrise.io?

**Comment by Shinichi52** [comment]
i fixed on my Mac :)

**Comment by viktorbenei** [comment]
Makes sense, thanks @Shinichi52 ! :)

**Comment by Shinichi52** [comment]
Hi, Can you add configure for upgrade fastlane. Example: if I don't want automatic upgrade fastlane can set false? I always have to manually upgrade when fastlane has new release.
Thank you very much :)

**Comment by viktorbenei** [comment]
Use the **Update deliver gem** (`update_deliver `) option of the step (https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/blob/master/step.yml#L170). If that's enabled the step will always try to upgrade `fastlane` before running.

**Comment by Shinichi52** [comment]
thank you :)
