### ISSUE TITLE
Upload to iTunesConnect Fails: Invalid characters in .ipa file name

### ISSUE THREAD

**Issue by justinvallely** [bitrise-io/steps-deploy-to-itunesconnect-deliver#26]
Looks to be related to [this.](https://github.com/fastlane/fastlane/issues/10327)

Deliver appends SHA256 to the original ipa name and copies it to transporter package. The resulting name of the file will be "ORIGINAL_IPA_NAME(SHA256).ipa". Parenthesis are not allowed in the .ipa file name.

`The valid characters are: A-Z, a-z, 0-9, dash, period, underscore, but the name cannot start with a dash, period, or underscore`

**Comment by trapacska** [comment]
Hey @justinvallely ! 👋

Thank you for the report, we've started to investigate the issue.

**Comment by trapacska** [comment]
Hey!

Thank you for reporting the issue!

It is already fixed: https://github.com/fastlane/fastlane/releases/tag/2.57.1
(this step always automatically updates fastlane to the latest)

I am closing the issue now but feel free to re-open if you encounter the issue again!
🎉🚀

**Comment by taxomania** [comment]
Hey guys, thanks for the above fix. Unfortunately it appears to continue breaking builds containing spaces in the IPA filename eg `"ORIGINAL IPA NAME.ipa"` :(

**Comment by viktorbenei** [comment]
@taxomania can you please create a new issue report with the logs?

**Comment by zackd** [comment]
@viktorbenei https://discuss.bitrise.io/t/upload-to-itunesconnect-fails/2752
