### ISSUE TITLE
Deliver's submit_for_review is for app review, not for beta review

### ISSUE THREAD

**Issue by davidchristiandy** [bitrise-io/steps-deploy-to-itunesconnect-deliver#31]
I noticed the "Submit for TestFlight External Testing" in `main.go` adds the flag `--submit_for_review`.

AFAIK, Deliver's `--submit_for_review` flag will submit the app for appstore review (i.e. not for beta review or external testing).

Some ideas to fix this:
- I think we can simply change copy from "Submit for TestFlight External Testing" to "Submit for Review" (and also the description text).
- "Submit for TestFlight External Testing"  is still achievable via Pilot. I don't think Deliver supports beta review, CMIIW.

what do you think?

**Comment by doomsayer13** [comment]
Thanks for reporting.

**Comment by davidchristiandy** [comment]
Sure, @doomsayer13. Anyways, what do you think on this problem? I might have some time this weekend to work on this issue. Any comments on my proposed ideas, before I start hacking?
