### ISSUE TITLE
2FA Support via Apple developer connected account

### ISSUE THREAD

**Issue by joeltrewlush** [bitrise-io/steps-deploy-to-itunesconnect-deliver#33]
Bitrise's new ios-auto-provisoning step uses a connected apple developer account to create/access the required provisioning profiles when signing a build, when connecting an account 2FA details are saved and handled by bitrise. Is it possible for this step to use the same connected account information to bypass 2FA in a similar way? It should be noted that any new Apple accounts cannot turn off 2FA, so disabling 2FA is no longer an option.

Thanks

**Comment by BerniWittmann** [comment]
I also have issues with 2FA. As a solution to 2FA Apple has `Application specific password` (You can generate them on [AppleID Homepage](https://appleid.apple.com). 

The problem I'm having is that the authentication with itunes connect does not work, when using the application specific password. Fastlane has an env variable for this: `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` (Also see the [FAQ to 2FA from fastlane](https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification)). 

I'll try and push a pull request for this, hopefully it works with that

**Comment by viktorbenei** [comment]
Awesome idea and thanks for the PR @BerniWittmann ! I added a comment to the PR and the tooling team will also review the PR ASAP! :)

**Comment by mqln** [comment]
Hello! Where are we at on this?

I'm afraid I broke my entire workflow up upgrading to 2FA auth...

**Comment by fehersanyi-bitrise** [comment]
Hello @mqln!

did you connect your apple account to bitrise on the account settings tab? it pops up a 6 digit code that you enter there and you are good to go in regards of 2fa.
