### ISSUE TITLE
Upload not working due to old fastlane tool

### ISSUE THREAD

**Issue by Dschee** [bitrise-io/steps-deploy-to-itunesconnect-deliver#46]
We are currently receiving errors when trying to upload builds using this step since it uses an old version of Fastlane and Apple changed something. See https://github.com/fastlane/fastlane/issues/12577 for details. There's a fix though in the newest release [2.96.0](https://github.com/fastlane/fastlane/releases), could you please update this to the latest version of fastlane?

**Comment by trapacska** [comment]
Hey @Dschee !

The step uses the version you've set. Set the desired version in the `fastlane_version` or leave latest of you want that. It should do the trick. Please let me know if it helps.

**Comment by joshdholtz** [comment]
Heyyyyy 👋 Version `2.96.0` doesn't _technically_ fix the problem but only shows a prettier error for the solution 🙃 Older versions of _fastlane_ should still work but you just need to do this step - https://github.com/fastlane/fastlane/issues/12577#issuecomment-390811299 (this is what `2.96.0` informs users of)

**Comment by Dschee** [comment]
Cool thanks, didn't know one could specify a specific version. I'd like to specify something like `latest` though, which I did by manually adding a script that runs `gem install fastlane` before the deploy step. That's working like expected.

And while you @joshdholtz are of course technically right, I'd like to disagree: It *does* fix the problem since my CI is now telling me how I can fix it which wasn't the case before. Regarding a CI, for me this is a fix. But that's discussable of course. :)

**Comment by trapacska** [comment]
Thanks @Dschee for getting back. Also @joshdholtz and @viktorbenei for the info.

Closing this issue now as it seems not to be an exact issue with the step itself. Feel free to re-open if you still encounter issues regarding to the step.
