### ISSUE TITLE
Spaceship::UnexpectedResponse

### ISSUE THREAD

**Issue by hantran-yamaneco** [bitrise-io/steps-deploy-to-itunesconnect-deliver#53]
It's really weird that I got below messages when trying to deploy out tvOS app to TestFlight, it work fine with my local (Archive and Upload from xCode).

`
[02:14:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[02:14:53]: Sending anonymous analytics information
[02:14:53]: Learn more at https://docs.fastlane.tools/#metrics
[02:14:53]: No personal or sensitive data is sent.
[02:14:53]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[02:14:53]: Login to App Store Connect ([REDACTED])
[02:14:56]: Login successful
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/client.rb:602:in `parse_response': [!] <HTML><HEAD> (Spaceship::UnexpectedResponse)
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference #1.df04f17.1535620796.5cd4ba6d
</BODY></HTML>
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/tunes_client.rb:256:in `applications'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:67:in `all'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/tunes/application.rb:73:in `find'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/detect_values.rb:41:in `find_app'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/detect_values.rb:14:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/runner.rb:25:in `initialize'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/commands_generator.rb:79:in `new'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Deploy failed, error: exit status 1

`

**Comment by EgzonArifi** [comment]
Hi @hantran-yamaneco , which version are you using?
Try to update to latest version 2.14.1

**Comment by hantran-yamaneco** [comment]
I'm using the latest version but now it's not happening again (I don't know why). I'm going to close this issue.
