### ISSUE TITLE
Getting: Issue with input: no IpaPath nor PkgPath parameter specified

### ISSUE THREAD

**Issue by davidseek** [bitrise-io/steps-deploy-to-itunesconnect-deliver#57]
<img width="753" alt="screen shot 2018-11-17 at 7 06 34 pm" src="https://user-images.githubusercontent.com/17073950/48668174-fcfbf000-ea9b-11e8-9bc4-9849e6ac4398.png">

I'm not exactly sure what to do as those parameters seem
to be put in place by the step?

<img width="419" alt="screen shot 2018-11-17 at 7 06 41 pm" src="https://user-images.githubusercontent.com/17073950/48668176-038a6780-ea9c-11e8-936f-108cd4e24585.png">

**Comment by davidseek** [comment]
Hey @bitce 

does not look like they are set.
I would also not know right now what the expected values would be?
Is there a documentation for that specific part?

Thank you for your time.

**Comment by davidseek** [comment]
[This thread](https://stackoverflow.com/questions/33934614/bitrise-default-environment-variables) brought me to the fact that I needed to include the step `Xcode Archive & Export for iOS` into the workflow. One might say logically, but I expected this to be automatic when including a step that uploads to the store. Running the build right now. Will let you know if this fixed the issue.

**Comment by bitce** [comment]
Oh, I see. How did it go? :) For future reference, when in doubt, please check out our DevCenter, we have a bunch of very nice detailed articles to help you get started, e.g. https://devcenter.bitrise.io/deploy/ios-deploy/deploying-an-ios-app-to-itunes-connect/

**Comment by davidseek** [comment]
Yeah. Talking to you on the customer chat now to solve this :)
