### ISSUE TITLE
Build aborts because iTunes Connect still processing

### ISSUE THREAD

**Issue by Spence1115** [bitrise-io/steps-deploy-to-itunesconnect-deliver#9]
Hi

We've got apps building through Bitrise using this step, but the build aborts because it sometimes hits the 45 minutes whilst waiting for iTunes Connect to finish, as sometimes that part seems to take an hour or so. The app is uploaded fine, so is there any way we could get an option that tells this step on Bitrise to not wait for iTunes Connect to say its 100% finished?

**Comment by viktorbenei** [comment]
Yes, that's actually _disabled_ by default, I think you enabled it at some point, the option is: `submit_for_beta` - https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/blob/master/step.yml#L91

**Comment by Spence1115** [comment]
We've got that disabled already.

**Comment by viktorbenei** [comment]
Could you please send us the full build log in email / through onsite chat?
